name: ci
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:
permissions: write-all
jobs:
  miniflux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install --no-interaction
    - name: Run Python script
      env:
        MINIFLUX_TOKEN: ${{secrets.MINIFLUX_TOKEN}}
      run: poetry run --no-interaction python main.py
    - uses: EndBug/add-and-commit@v9
      with:
        add: data
        default_author: github_actions
  
